# Generated by Django 4.2.16 on 2026-07-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Avec_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent')], default='agent', max_length=20),
        ),
    ]
