# Generated by Django 4.2.16 on 2026-07-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Avec_App', '0002_utilisateur_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AddField(
            model_name='adhesion',
            name='devise',
            field=models.TextField(default='cdf'),
        ),
        migrations.AddField(
            model_name='compte',
            name='devise',
            field=models.TextField(default='cdf'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='devise',
            field=models.TextField(default='cdf'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='devise',
            field=models.TextField(default='cdf'),
        ),
        migrations.AddField(
            model_name='social',
            name='devise',
            field=models.TextField(default='cdf'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(max_length=20),
        ),
    ]
