# Generated by Django 6.1 on 2026-08-31 14:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Avec_App', '0003_remove_transaction_date_adhesion_devise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('devise', models.CharField(choices=[('cdf', 'CDF'), ('usd', 'USD')], default='cdf', max_length=3)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='devise',
            field=models.CharField(choices=[('cdf', 'CDF'), ('usd', 'USD')], default='cdf', max_length=3),
        ),
        migrations.AlterField(
            model_name='compte',
            name='devise',
            field=models.CharField(choices=[('cdf', 'CDF'), ('usd', 'USD')], default='cdf', max_length=3),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='devise',
            field=models.CharField(choices=[('cdf', 'CDF'), ('usd', 'USD')], default='cdf', max_length=3),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='devise',
            field=models.CharField(choices=[('cdf', 'CDF'), ('usd', 'USD')], default='cdf', max_length=3),
        ),
        migrations.AlterField(
            model_name='social',
            name='devise',
            field=models.CharField(choices=[('cdf', 'CDF'), ('usd', 'USD')], default='cdf', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
        migrations.CreateModel(
            name='CreditCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acompte_initial', models.DecimalField(decimal_places=2, default=0.0, help_text='Montant déposé au départ avant de retirer les produits', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('montant_total_panier', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Reste à payer', max_digits=12)),
                ('devise', models.CharField(choices=[('cdf', 'CDF'), ('usd', 'USD')], default='cdf', max_length=3)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_cantine', to='Api_Avec_App.member')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCreditCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire_applique', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('sous_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('credit_cantine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Api_Avec_App.creditcantine')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api_Avec_App.produitcantine')),
            ],
        ),
        migrations.CreateModel(
            name='RemboursementCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('devise', models.CharField(choices=[('cdf', 'CDF'), ('usd', 'USD')], default='cdf', max_length=3)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('credit_cantine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements_cantine', to='Api_Avec_App.creditcantine')),
            ],
        ),
    ]
